/**
 * Phase 6 — Mode 6 (Sudden Death) + Mode 7 (Mirror) parallel engine.
 * Replaces the Phase 2 soft-fail stub with a real state machine.
 *
 * Shape:
 *   - `createMatch` → phase `'setup'`, opponent secret generated by
 *     the mode (`mode.generateSecret(rng)`). For `flags.sharedSecret`
 *     modes (Mode 7) the caller-supplied `playerSecret` is **overwritten**
 *     with the generated value so `submitGuess`'s `targetSecret`
 *     resolution maps both sides to the shared string with zero
 *     parallel-specific branching downstream.
 *   - `startMatch` → phase `'active_parallel'`. NO "who starts" RNG
 *     draw (parallel has no turn rotation), which is the cursor-
 *     divergence point vs `turnBasedEngine.startMatch`. The CP3 parity
 *     test feeds explicit guess arrays so the divergence is invisible
 *     there; bot-driven runs across the two engines are NOT parity-
 *     comparable from the same seed.
 *   - `submitGuess` → validate, evaluate, append, decrement budget,
 *     `checkEndConditions`. On a terminal result phase flips to
 *     `'completed'`; otherwise phase stays `'active_parallel'` and the
 *     other side remains free to submit. **No `advanceTurn`.**
 *
 * Concurrency: in production, `matchStore.submitGuess` serializes calls
 * at the function-call boundary, so the first crack flips
 * `phase=completed` and a racing second submission hits the
 * `'completed'` throw below. The `simultaneous_crack → draw` branch in
 * `checkEndConditions` is therefore only reachable from a constructed
 * test state (both sides pre-seeded with winning feedback). The test
 * suite calls this out explicitly; it's not a code bug, it's an
 * asymmetry vs turn-based that's worth flagging at the seam.
 *
 * Errors: a `submitGuess` against a `'completed'` or `'setup'` state
 * throws `InvalidEngineStateError` — same invariant as
 * `turnBasedEngine`. The Phase 2 soft-fail behaviour ("warn + return
 * identity") was correct only while the engine was unimplemented; now
 * a misrouted call is a programmer error, not a known gap.
 */

import { createRNG } from '@/lib/random';

import { InvalidEngineStateError } from '../errors';
import { modeRegistry } from '../modeRegistry';
import type {
  ClockSnapshot,
  GuessEntry,
  GuessSide,
  MatchState,
  ModeDefinition,
  RNG,
  RNGStateSnapshot,
} from '../types';
import { checkEndConditions } from './checkEndConditions';
import type { SubmitGuessResult } from './turnBasedEngine';

export function createMatch(
  modeId: number,
  playerSecret: string,
  rngState: RNGStateSnapshot,
): MatchState {
  const mode = modeRegistry.get(modeId);
  const rng = createRNG(rngState);
  // Generate FIRST, then mirror. RNG consumption is identical between
  // sharedSecret-true and sharedSecret-false parallel modes — important
  // so a future "Mirror with player-set secret" variant doesn't have a
  // divergent RNG profile from Mode 7.
  const opponentSecret = mode.generateSecret(rng);
  const finalPlayerSecret =
    mode.rules.flags.sharedSecret === true ? opponentSecret : playerSecret;
  const now = Date.now();
  const baseState: MatchState = {
    modeId,
    playerSecret: finalPlayerSecret,
    opponentSecret,
    playerGuesses: [],
    opponentGuesses: [],
    phase: 'setup',
    result: null,
    rngState: rng.getState(),
    startedAt: now,
    lastUpdatedAt: now,
    ...buildModeBaseExtras(mode),
  };
  return baseState;
}

function buildModeBaseExtras(mode: ModeDefinition): Pick<MatchState, 'guessLimits'> | object {
  const max = mode.rules.maxGuessesPerPlayer;
  if (max !== undefined) {
    return {
      guessLimits: { playerRemaining: max, opponentRemaining: max },
    };
  }
  return {};
}

/**
 * Move from `'setup'` to `'active_parallel'` and pre-build the bot's
 * solver state. Unlike `turnBasedEngine.startMatch`, this consumes
 * **zero** RNG — there is no "who starts" question in a parallel race.
 * That divergence is intentional and load-bearing (see file header).
 */
export function startMatch(state: MatchState, rng: RNG): MatchState {
  if (state.phase !== 'setup') {
    throw new InvalidEngineStateError(
      `startMatch called on phase '${state.phase}' (expected 'setup')`,
    );
  }
  const mode = modeRegistry.get(state.modeId);
  const opponentSolver = mode.bot.initSolverState(state.opponentSecret, mode.rules);
  // Phase 7A.2 wires DDA at `matchStore.createMatch` (stamps
  // `state.botDifficulty` from `pickDifficultyFromOutcomes(userStore
  // .stats.recentMatches)`). The engine stays userStore-naïve; the
  // `?? 'normal'` fallback covers the resume path where state was
  // hydrated mid-match and tests that construct state directly. Mode 6
  // (`makeGuess`) and Mode 7 (`makeGuess` + `thinkingTime`) both reuse
  // `mode1/bot.ts`, which consumes `ctx.difficulty` — so DDA reaches
  // every mode through this stamp without per-mode wiring.
  const botDifficulty = state.botDifficulty ?? 'normal';
  const now = Date.now();
  return {
    ...state,
    phase: 'active_parallel',
    botDifficulty,
    // `firstAuthor='self'` is the player-POV default. Mode 7 hides the
    // opponent timeline entirely (CP4 filter) so the field is unread;
    // Mode 6 parallel still surfaces interleaved rows, and 'self'
    // matches a viewer-anchored chronology.
    firstAuthor: state.firstAuthor ?? 'self',
    solverStates: {
      ...(state.solverStates ?? {}),
      opponent: opponentSolver,
    },
    rngState: rng.getState(),
    lastUpdatedAt: now,
  };
}

/**
 * Validate, evaluate, append, end-check. Returns `error` on validation
 * failure (state untouched); returns updated state with terminal
 * `result` when `checkEndConditions` fires; otherwise keeps phase at
 * `'active_parallel'` for the next submission from either side.
 *
 * Mode 7 (`flags.sharedSecret`): `state.playerSecret === state.opponentSecret`
 * after `createMatch`, so `targetSecret = author === 'self' ? opponentSecret : playerSecret`
 * resolves to the same string for both sides — no parallel-specific
 * branch needed inside this function.
 */
export async function submitGuess(
  state: MatchState,
  guess: string,
  author: GuessSide,
  rng: RNG,
): Promise<SubmitGuessResult> {
  if (state.phase === 'completed' || state.phase === 'setup') {
    throw new InvalidEngineStateError(`submitGuess called on phase '${state.phase}'`);
  }
  const mode = modeRegistry.get(state.modeId);
  const validation = mode.validateGuess(guess);
  if (!validation.ok) {
    return { state, feedback: null, error: validation.error };
  }

  const targetSecret = author === 'self' ? state.opponentSecret : state.playerSecret;
  const feedback = mode.evaluate(guess, targetSecret);

  const guessIndex =
    (author === 'self' ? state.playerGuesses.length : state.opponentGuesses.length) + 1;
  // `createdAt` is the chronological ordering key consumed by
  // `interleaveTimeline({chronological:true})`. We capture once so the
  // entry timestamp + the state's `lastUpdatedAt` stay coherent — a
  // separate `Date.now()` call would let those two fields diverge by
  // milliseconds depending on JS engine scheduling.
  const submittedAt = Date.now();
  const entry: GuessEntry = {
    side: author,
    guessIndex,
    digits: parseDigits(guess),
    feedback,
    createdAt: submittedAt,
  };

  let newState: MatchState = {
    ...state,
    playerGuesses: author === 'self' ? [...state.playerGuesses, entry] : state.playerGuesses,
    opponentGuesses:
      author === 'opponent' ? [...state.opponentGuesses, entry] : state.opponentGuesses,
    rngState: rng.getState(),
    lastUpdatedAt: submittedAt,
  };

  if (mode.rules.maxGuessesPerPlayer !== undefined && newState.guessLimits) {
    newState = {
      ...newState,
      guessLimits: decrementLimit(newState.guessLimits, author),
    };
  }

  const result = checkEndConditions(newState, mode);
  if (result !== null) {
    return {
      state: { ...newState, phase: 'completed', result },
      feedback,
      error: null,
    };
  }

  // No `advanceTurn` — phase stays `'active_parallel'`. The other side
  // can submit at any time. Single-side budget exhaustion is non-
  // terminal in Mode 6 parallel (SPEC §3.10): the trailing side keeps
  // submitting until they too hit zero, at which point
  // `checkEndConditions`'s `both exhausted → stalemate` branch fires.
  return {
    state: newState,
    feedback,
    error: null,
  };
}

/**
 * Parallel modes (Mode 6 + Mode 7) carry no per-player time limit
 * today, so `applyTimeout` is unreachable in their normal flow.
 * Returns the state unchanged for defensive callers — no warn (the
 * Phase 2 stub's "Faz 6 pending" message is no longer accurate).
 */
export function applyTimeout(state: MatchState, _mode: ModeDefinition): MatchState {
  return state;
}

/**
 * No clock semantics in parallel modes today. Future timed parallel
 * variants (e.g. Mirror Blitz) would extend the engine here.
 */
export function applyClockSnapshot(state: MatchState, _snapshot: ClockSnapshot): MatchState {
  return state;
}

// ─────────────────────────────────────────────────────────────
// Internal helpers — duplicated from `turnBasedEngine` deliberately.
// Both engines rely on the same trivial primitives (5 + 13 lines);
// extracting to a shared module would touch turnBasedEngine for zero
// behaviour change and create a synchronization seam for nothing.
// ─────────────────────────────────────────────────────────────

function parseDigits(guess: string): readonly number[] {
  const out: number[] = [];
  for (const ch of guess) out.push(Number.parseInt(ch, 10));
  return out;
}

function decrementLimit(
  current: { readonly playerRemaining: number; readonly opponentRemaining: number },
  author: GuessSide,
): { readonly playerRemaining: number; readonly opponentRemaining: number } {
  if (author === 'self') {
    return {
      ...current,
      playerRemaining: Math.max(0, current.playerRemaining - 1),
    };
  }
  return {
    ...current,
    opponentRemaining: Math.max(0, current.opponentRemaining - 1),
  };
}
