/**
 * Mode-agnostic turn-based engine. Drives Modes 1–6. The engine is
 * *event-driven only* — there is no `tick()` here. Wall-clock
 * orchestration (Mode 4 Blitz countdown) is owned by `liveMatchStore`
 * and the `MatchScreen` setInterval; on timeout the screen calls
 * `applyTimeout(state)` which goes through `checkEndConditions`.
 *
 * Engines never touch React, AsyncStorage, or any UI primitive. The
 * only async surface is `submitGuess`, which is `Promise`-typed so
 * heavy modes (Mode 3, Mode 5) can chunk their bot work without
 * forcing a wider refactor later.
 */

import { createRNG } from '@/lib/random';

import { InvalidEngineStateError } from '../errors';
import { modeRegistry } from '../modeRegistry';
import { generateRandomDigits } from '../shared/secretGeneration';
import type {
  ClockSnapshot,
  GuessEntry,
  GuessSide,
  MatchState,
  ModeDefinition,
  NormalizedFeedback,
  RNG,
  RNGStateSnapshot,
  ValidationError,
} from '../types';
import { checkEndConditions } from './checkEndConditions';

export interface SubmitGuessResult {
  readonly state: MatchState;
  readonly feedback: NormalizedFeedback | null;
  readonly error: ValidationError | null;
}

/**
 * Bootstrap a `MatchState` for the given mode. The opponent secret is
 * generated by the mode (uses the supplied RNG so the call count is
 * captured in `rngState`). Phase = `'setup'` until `startMatch` flips it.
 */
export function createMatch(
  modeId: number,
  playerSecret: string,
  rngState: RNGStateSnapshot,
): MatchState {
  const mode = modeRegistry.get(modeId);
  const rng = createRNG(rngState);
  const opponentSecret = mode.generateSecret(rng);
  const now = Date.now();
  const baseState: MatchState = {
    modeId,
    playerSecret,
    opponentSecret,
    playerGuesses: [],
    opponentGuesses: [],
    phase: 'setup',
    result: null,
    rngState: rng.getState(),
    startedAt: now,
    lastUpdatedAt: now,
    ...buildModeBaseExtras(mode),
  };
  return baseState;
}

function buildModeBaseExtras(mode: ModeDefinition): Pick<MatchState, 'guessLimits'> | object {
  const max = mode.rules.maxGuessesPerPlayer;
  if (max !== undefined) {
    return {
      guessLimits: { playerRemaining: max, opponentRemaining: max },
    };
  }
  return {};
}

/**
 * Move from `'setup'` to whichever side starts. Picks turn owner with
 * RNG and pre-builds the bot's solver state via `mode.bot.initSolverState`.
 */
export function startMatch(state: MatchState, rng: RNG): MatchState {
  if (state.phase !== 'setup') {
    throw new InvalidEngineStateError(
      `startMatch called on phase '${state.phase}' (expected 'setup')`,
    );
  }
  const mode = modeRegistry.get(state.modeId);
  const playerStarts = rng.next() < 0.5;
  const phase = playerStarts ? 'active_turn_player' : 'active_turn_opponent';
  const opponentSolver = mode.bot.initSolverState(state.opponentSecret, mode.rules);
  // TODO(phase-7A): replace with `selectDifficulty(userStore.stats)` per
  // SPEC §5.5. Phase 3 hardcodes 'normal' so the bot is stable while the
  // economy + DDA wiring is still mock-driven.
  const botDifficulty = state.botDifficulty ?? 'normal';
  return {
    ...state,
    phase,
    botDifficulty,
    firstAuthor: state.firstAuthor ?? (playerStarts ? 'self' : 'opponent'),
    solverStates: {
      ...(state.solverStates ?? {}),
      opponent: opponentSolver,
    },
    rngState: rng.getState(),
    lastUpdatedAt: Date.now(),
  };
}

/**
 * Validate, evaluate, append, end-check, advance. Returns `error` on
 * validation failure (state untouched); returns updated state on
 * success including any terminal `result`.
 */
export async function submitGuess(
  state: MatchState,
  guess: string,
  author: GuessSide,
  rng: RNG,
): Promise<SubmitGuessResult> {
  if (state.phase === 'completed' || state.phase === 'setup') {
    throw new InvalidEngineStateError(`submitGuess called on phase '${state.phase}'`);
  }
  const mode = modeRegistry.get(state.modeId);
  const validation = mode.validateGuess(guess);
  if (!validation.ok) {
    return { state, feedback: null, error: validation.error };
  }

  const targetSecret = author === 'self' ? state.opponentSecret : state.playerSecret;
  const feedback = mode.evaluate(guess, targetSecret);

  const guessIndex =
    (author === 'self' ? state.playerGuesses.length : state.opponentGuesses.length) + 1;
  const entry: GuessEntry = {
    side: author,
    guessIndex,
    digits: parseDigits(guess),
    feedback,
  };

  let newState: MatchState = {
    ...state,
    playerGuesses: author === 'self' ? [...state.playerGuesses, entry] : state.playerGuesses,
    opponentGuesses:
      author === 'opponent' ? [...state.opponentGuesses, entry] : state.opponentGuesses,
    rngState: rng.getState(),
    lastUpdatedAt: Date.now(),
  };

  if (mode.rules.maxGuessesPerPlayer !== undefined && newState.guessLimits) {
    newState = {
      ...newState,
      guessLimits: decrementLimit(newState.guessLimits, author),
    };
  }

  const result = checkEndConditions(newState, mode);
  if (result !== null) {
    return {
      state: { ...newState, phase: 'completed', result },
      feedback,
      error: null,
    };
  }

  return {
    state: advanceTurn(newState),
    feedback,
    error: null,
  };
}

/** Flip the active-turn phase. No-op for parallel modes (engine isn't used there). */
export function advanceTurn(state: MatchState): MatchState {
  if (state.phase === 'active_turn_player') {
    return { ...state, phase: 'active_turn_opponent', lastUpdatedAt: Date.now() };
  }
  if (state.phase === 'active_turn_opponent') {
    return { ...state, phase: 'active_turn_player', lastUpdatedAt: Date.now() };
  }
  return state;
}

/**
 * Mode 4 — collapse the match because a clock hit zero. Uses the
 * already-set `clockSnapshot` to drive `checkEndConditions`. The
 * snapshot must reflect the timeout (caller writes ≤0 before
 * invoking).
 */
export function applyTimeout(state: MatchState, mode: ModeDefinition): MatchState {
  if (state.phase === 'completed') return state;
  const result = checkEndConditions(state, mode);
  if (result === null) {
    throw new InvalidEngineStateError(
      'applyTimeout called but checkEndConditions did not produce a terminal result',
    );
  }
  return {
    ...state,
    phase: 'completed',
    result,
    lastUpdatedAt: Date.now(),
  };
}

/**
 * Persist a clock reading on the durable state right before a guess
 * goes in. The live tick value sits in `liveMatchStore` between
 * snapshots; this is the cross-store sync point.
 */
export function applyClockSnapshot(state: MatchState, snapshot: ClockSnapshot): MatchState {
  return {
    ...state,
    clockSnapshot: snapshot,
    lastUpdatedAt: Date.now(),
  };
}

// ─────────────────────────────────────────────────────────────
// Internal helpers
// ─────────────────────────────────────────────────────────────

function parseDigits(guess: string): readonly number[] {
  const out: number[] = [];
  for (const ch of guess) out.push(Number.parseInt(ch, 10));
  return out;
}

function decrementLimit(
  current: { readonly playerRemaining: number; readonly opponentRemaining: number },
  author: GuessSide,
): { readonly playerRemaining: number; readonly opponentRemaining: number } {
  if (author === 'self') {
    return {
      ...current,
      playerRemaining: Math.max(0, current.playerRemaining - 1),
    };
  }
  return {
    ...current,
    opponentRemaining: Math.max(0, current.opponentRemaining - 1),
  };
}

/**
 * Re-export for tests + parallelEngine that need a fresh RNG drawing
 * from `Date.now`-style entropy when the caller didn't pass one.
 * Keeps the entropy source on the `lib/random` boundary.
 */
export function generateOpponentSecret(mode: ModeDefinition, rng: RNG): string {
  // Defensive — fallthrough used by the parallel engine + tests when
  // the mode hasn't been registered yet (registry-free paths).
  return generateRandomDigits(mode.rules.secretLength, mode.rules.digitsUnique, rng);
}
